### ISSUE TITLE
Docker local Glue + Minio panics with NotSupported("Object store protocol") 

### ISSUE THREAD

**Issue by ForeverAngry** [JanKaul/iceberg-rust#68]
Hi Jan, I am trying to re-perform you "insert_table.rs" example for Iceberg, but using Glue as the catalog.  However, I cant seem to get past this error.  Am i doing something wrong here, or missing something?   I've tried a few different approaches, but i get the same error.  Any thoughts? 

## Stack Trace:

```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 27.36s
Running `target\debug\examples\crud_end_to_end_demo.exe`
thread 'main' panicked at iceberg-glue-catalog\src\lib.rs:907:50:
called `Result::unwrap()` on an `Err` value: NotSupported("Object store protocol")
stack backtrace:
0: std::panicking::begin_panic_handler
        at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
1: core::panicking::panic_fmt
        at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
2: core::result::unwrap_failed
        at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\result.rs:1700
3: enum2$<core::result::Result<alloc::sync::Arc<dyn$<object_store::ObjectStore>,alloc::alloc::Global>,enum2$<iceberg_rust::error::Error> > >::unwrap
        at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1104
4: iceberg_glue_catalog::impl$2::object_store
        at .\iceberg-glue-catalog\src\lib.rs:907
5: iceberg_glue_catalog::impl$2::create_table::async_block$0
        at .\iceberg-glue-catalog\src\lib.rs:294
6: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<iceberg_rust::table::Table,enum2$<iceberg_rust::error::Error> > > > >,core::marker::Send>,alloc::alloc::Global> >
        at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\future.rs:123
7: iceberg_rust::catalog::create::impl$0::build::async_fn$0
        at .\iceberg-rust\src\catalog\create.rs:82
8: crud_end_to_end_demo::main::async_block$0
        at .\datafusion_iceberg\examples\crud_end_to_end_demo.rs:90
9: core::future::future::impl$1::poll<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> >
        at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\future.rs:123
10: tokio::runtime::park::impl$4::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\park.rs:281
11: tokio::runtime::coop::with_budget
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\coop.rs:107
12: tokio::runtime::coop::budget
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\coop.rs:73
13: tokio::runtime::park::CachedParkThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\park.rs:281
14: tokio::runtime::context::blocking::BlockingRegionGuard::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\context\blocking.rs:66
15: tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\scheduler\multi_thread\mod.rs:87
16: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >,tuple$<> >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\context\runtime.rs:65
17: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\scheduler\multi_thread\mod.rs:86
18: tokio::runtime::runtime::Runtime::block_on_inner<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\runtime.rs:370
19: tokio::runtime::runtime::Runtime::block_on<enum2$<crud_end_to_end_demo::main::async_block_env$0> >
        at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\runtime.rs:340
20: crud_end_to_end_demo::main
        at .\datafusion_iceberg\examples\crud_end_to_end_demo.rs:170
21: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
        at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
22: core::hint::black_box
        at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\hint.rs:389
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\crud_end_to_end_demo.exe` (exit code: 101)
```

## Program code

```
use datafusion::{arrow::array::Int64Array, prelude::SessionContext};
use datafusion_iceberg::DataFusionTable;
use iceberg_glue_catalog::GlueCatalog;
use iceberg_rust::{
    catalog::bucket::ObjectStoreBuilder,
    spec::{
        partition::{PartitionField, PartitionSpec, Transform},
        schema::Schema,
        types::{PrimitiveType, StructField, StructType, Type},
    },
    table::Table,
};


use std::sync::Arc;
use aws_config::BehaviorVersion;

#[tokio::main]
pub(crate) async fn main() {

    let object_store = ObjectStoreBuilder::aws()
    .with_config("aws_access_key_id".parse().unwrap(), "minioadmin")
    .with_config("aws_secret_access_key".parse().unwrap(), "minioadmin")
    .with_config("endpoint".parse().unwrap(), "http://127.0.0.1:9000");

    let config = aws_config::defaults(BehaviorVersion::v2024_03_28())
        .region("us-east-1")
        .endpoint_url("http://127.0.0.1:9000")
        .test_credentials().load().await;

    let catalog = Arc::new(GlueCatalog::new(&config, "warehouse", object_store).unwrap());
 

    let schema = Schema::builder()
        .with_fields(
            StructType::builder()
                .with_struct_field(StructField {
                    id: 1,
                    name: "id".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Long),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 2,
                    name: "customer_id".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Long),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 3,
                    name: "product_id".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Long),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 4,
                    name: "date".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Date),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 5,
                    name: "amount".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Int),
                    doc: None,
                })
                .build()
                .unwrap(),
        )
        .build()
        .unwrap();

    let partition_spec = PartitionSpec::builder()
        .with_partition_field(PartitionField::new(4, 1000, "day", Transform::Day))
        .build()
        .expect("Failed to create partition spec");

    let table = Table::builder()
        .with_name("orders")
        .with_location("/warehouse/raw")
        .with_schema(schema)
        .with_partition_spec(partition_spec)
        .build(&["warehouse".to_owned()], catalog)
        .await
        .expect("Failed to create table");

    let table = Arc::new(DataFusionTable::from(table));

    let ctx = SessionContext::new();

    ctx.register_table("orders", table).unwrap();

    ctx.sql(
        "INSERT INTO orders (id, customer_id, product_id, date, amount) VALUES 
        (1, 1, 1, '2020-01-01', 1),
        (2, 2, 1, '2020-01-01', 1),
        (3, 3, 1, '2020-01-01', 3),
        (4, 1, 2, '2020-02-02', 1),
        (5, 1, 1, '2020-02-02', 2),
        (6, 3, 3, '2020-02-02', 3);",
    )
    .await
    .expect("Failed to create query plan for insert")
    .collect()
    .await
    .expect("Failed to insert values into table");

    let batches = ctx
        .sql("select product_id, sum(amount) from orders group by product_id;")
        .await
        .expect("Failed to create plan for select")
        .collect()
        .await
        .expect("Failed to execute select query");

    for batch in batches {
        if batch.num_rows() != 0 {
            let (product_ids, amounts) = (
                batch
                    .column(0)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .unwrap(),
                batch
                    .column(1)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .unwrap(),
            );
            for (product_id, amount) in product_ids.iter().zip(amounts) {
                if product_id.unwrap() == 1 {
                    assert_eq!(amount.unwrap(), 7)
                } else if product_id.unwrap() == 2 {
                    assert_eq!(amount.unwrap(), 1)
                } else if product_id.unwrap() == 3 {
                    assert_eq!(amount.unwrap(), 3)
                } else {
                    panic!("Unexpected product id")
                }
            }
        }
    }

    ctx.sql(
        "INSERT INTO orders (id, customer_id, product_id, date, amount) VALUES 
        (7, 1, 3, '2020-01-03', 1),
        (8, 2, 1, '2020-01-03', 2),
        (9, 2, 2, '2020-01-03', 1);",
    )
    .await
    .expect("Failed to create query plan for insert")
    .collect()
    .await
    .expect("Failed to insert values into table");

    let batches = ctx
        .sql("select product_id, sum(amount) from orders group by product_id;")
        .await
        .expect("Failed to create plan for select")
        .collect()
        .await
        .expect("Failed to execute select query");

    for batch in batches {
        if batch.num_rows() != 0 {
            let (product_ids, amounts) = (
                batch
                    .column(0)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .unwrap(),
                batch
                    .column(1)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .unwrap(),
            );
            for (product_id, amount) in product_ids.iter().zip(amounts) {
                if product_id.unwrap() == 1 {
                    assert_eq!(amount.unwrap(), 9)
                } else if product_id.unwrap() == 2 {
                    assert_eq!(amount.unwrap(), 2)
                } else if product_id.unwrap() == 3 {
                    assert_eq!(amount.unwrap(), 4)
                } else {
                    panic!("Unexpected product id")
                }
            }
        }
    }
}

```

## docker-compose file

```
services:
  glue:
    container_name: glue_jupyter
    command: /home/glue_user/jupyter/jupyter_start.sh && sudo chown -R 10000:10000 /home/glue_user/workspace/jupyter_workspace
    environment:
      - DISABLE_SSL=true
      - AWS_PROFILE=glue
      - DATALAKE_FORMATS=iceberg
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    ports:
      # Spark web UI
      - '4040:4040' 
      - '4041:4041'
      # Spark History server
      - '28080:18080'
      - '28081:18081'
      # Jupyter web server
      - '8998:8998'
      - '8888:8888'
    restart: always

  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DOMAIN=minio
    networks:
      default:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  aws:
    image: amazon/aws-cli
    hostname: aws-cli
    container_name: aws-cli
    volumes:
      - ./data:/home/data
    command: |
      -c "sleep 2 && \
      aws --endpoint-url http://minio:9000 s3 mb s3://warehouse --region us-east-1 ; \
      aws --endpoint-url http://minio:9000 s3 cp /home/data s3://warehouse/raw --recursive"
    entrypoint: [/bin/bash]
    environment: 
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
    depends_on: 
      - minio
```

**Comment by JanKaul** [comment]
Could you try "s3://warehouse/raw" as the location for the table?

**Comment by ForeverAngry** [comment]
@JanKaul  Yeah that did the trick, and got me past that issue.  But for about the last day ive been trying to figure out this dispatch error.  I think its related to the glue configuration im running.  what do you think?

## Stack trace
```
Failed to create table: InvalidFormat("dispatch failure")
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\result.rs:1700
   3: enum2$<core::result::Result<iceberg_rust::table::Table,enum2$<iceberg_rust::error::Error> > >::expect<iceberg_rust::table::Table,enum2$<iceberg_rust::error::Error> >
             at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1061
   4: crud_end_to_end_demo::main::async_block$0
             at .\datafusion_iceberg\examples\crud_end_to_end_demo.rs:101
   5: core::future::future::impl$1::poll<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> >
             at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\future.rs:123
   6: tokio::runtime::park::impl$4::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\park.rs:281
   7: tokio::runtime::coop::with_budget
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\coop.rs:107
   8: tokio::runtime::coop::budget
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\coop.rs:73
   9: tokio::runtime::park::CachedParkThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\park.rs:281
  10: tokio::runtime::context::blocking::BlockingRegionGuard::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\context\blocking.rs:66
  11: tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\scheduler\multi_thread\mod.rs:87
  12: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >,tuple$<> >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\context\runtime.rs:65
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\scheduler\multi_thread\mod.rs:86
  14: tokio::runtime::runtime::Runtime::block_on_inner<core::pin::Pin<alloc::boxed::Box<enum2$<crud_end_to_end_demo::main::async_block_env$0>,alloc::alloc::Global> > >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\runtime.rs:370
  15: tokio::runtime::runtime::Runtime::block_on<enum2$<crud_end_to_end_demo::main::async_block_env$0> >
             at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.41.1\src\runtime\runtime.rs:340
  16: crud_end_to_end_demo::main
             at .\datafusion_iceberg\examples\crud_end_to_end_demo.rs:187
  17: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
  18: core::hint::black_box
             at C:\Users\User\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\hint.rs:389
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Rust Source Code
```

use aws_config::BehaviorVersion;
use aws_sdk_glue::Error;
use datafusion::{arrow::array::Int64Array, prelude::SessionContext};
use std::sync::Arc;
use datafusion_iceberg::DataFusionTable;
use iceberg_glue_catalog::GlueCatalog;
use iceberg_rust::{
    catalog::bucket::{ConfigKey, ObjectStoreBuilder},
    spec::{
        partition::{PartitionField, PartitionSpec, Transform},
        schema::Schema,
        types::{PrimitiveType, StructField, StructType, Type},
    },
    table::Table,
};
use object_store::{aws::{AmazonS3Builder, AmazonS3ConfigKey}, ClientConfigKey};


#[tokio::main]
pub(crate) async fn main() {
        let object_store = ObjectStoreBuilder::S3(AmazonS3Builder::new()
        .with_access_key_id("minioadmin".to_string())
        .with_secret_access_key("minioadmin".to_string())
        .with_endpoint("http://localhost:9000")
        .with_region("us-east-1".to_string())
    );
    let allow_http = ConfigKey::AWS(
        AmazonS3ConfigKey::Client(
                ClientConfigKey::AllowHttp,
            )
        );
    
    let allow_certs = ConfigKey::AWS(
        AmazonS3ConfigKey::Client(
            ClientConfigKey::AllowInvalidCertificates
        )
    );

    let config = aws_types::SdkConfig::builder()
    .behavior_version(BehaviorVersion::latest())
    .region(Some(aws_sdk_s3::config::Region::new("us-east-1")))
    .endpoint_url("http://localhost:8888".to_string())
    .retry_config(aws_config::retry::RetryConfig::standard())
    .build();

    let catalog = Arc::new(GlueCatalog::new(&config, "warehouse", object_store.with_config(allow_certs, "true".to_string()).with_config(allow_http, "true".to_string()))
        .expect("Failed to create GlueCatalog"));

    println!("Catalog created");

    let schema = Schema::builder()
        .with_fields(
            StructType::builder()
                .with_struct_field(StructField {
                    id: 1,
                    name: "id".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Long),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 2,
                    name: "customer_id".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Long),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 3,
                    name: "product_id".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Long),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 4,
                    name: "date".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::String),
                    doc: None,
                })
                .with_struct_field(StructField {
                    id: 5,
                    name: "amount".to_string(),
                    required: true,
                    field_type: Type::Primitive(PrimitiveType::Int),
                    doc: None,
                })
                .build()
                .expect("Failed to create StructType"),
        )
        .build()
        .expect("Failed to create Schema");

    let partition_spec = PartitionSpec::builder()
        .with_partition_field(PartitionField::new(4, 1000, "day", Transform::Day))
        .build()
        .expect("Failed to create partition spec");

    let table = Table::builder()
        .with_name("orders")
        .with_location("s3://warehouse/")
        .with_schema(schema)
        .with_partition_spec(partition_spec)
        .build(&["warehouse".to_string()], catalog)
        .await
        .expect("Failed to create table");

    let table = Arc::new(DataFusionTable::from(table));

    let ctx = SessionContext::new();

    ctx.register_table("orders", table).expect("Failed to register table");

    ctx.sql(
        "INSERT INTO orders (id, customer_id, product_id, date, amount) VALUES 
        (1, 1, 1, '2020-01-01', 1),
        (2, 2, 1, '2020-01-01', 1),
        (3, 3, 1, '2020-01-01', 3),
        (4, 1, 2, '2020-02-02', 1),
        (5, 1, 1, '2020-02-02', 2),
        (6, 3, 3, '2020-02-02', 3);",
    )
    .await
    .expect("Failed to create query plan for insert")
    .collect()
    .await
    .expect("Failed to insert values into table");

    let batches = ctx
        .sql("select product_id, sum(amount) from orders group by product_id;")
        .await
        .expect("Failed to create plan for select")
        .collect()
        .await
        .expect("Failed to execute select query");

    batches.into_iter().for_each(|batch| {
        if batch.num_rows() != 0 {
            let (product_ids, amounts) = (
                batch
                    .column(0)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .expect("Failed to downcast product_id column"),
                batch
                    .column(1)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .expect("Failed to downcast amount column"),
            );
            for (product_id, amount) in product_ids.iter().zip(amounts) {
                if product_id.unwrap() == 1 {
                    assert_eq!(amount.unwrap(), 7)
                } else if product_id.unwrap() == 2 {
                    assert_eq!(amount.unwrap(), 1)
                } else if product_id.unwrap() == 3 {
                    assert_eq!(amount.unwrap(), 3)
                } else {
                    panic!("Unexpected product id")
                }
            }
        }
    });

    ctx.sql(
        "INSERT INTO orders (id, customer_id, product_id, date, amount) VALUES 
        (7, 1, 3, '2020-01-03', 1),
        (8, 2, 1, '2020-01-03', 2),
        (9, 2, 2, '2020-01-03', 1);",
    )
    .await
    .expect("Failed to create query plan for insert")
    .collect()
    .await
    .expect("Failed to insert values into table");

    let batches = ctx
        .sql("select product_id, sum(amount) from orders group by product_id;")
        .await
        .expect("Failed to create plan for select")
        .collect()
        .await
        .expect("Failed to execute select query");

    for batch in batches {
        if batch.num_rows() != 0 {
            let (product_ids, amounts) = (
                batch
                    .column(0)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .expect("Failed to downcast product_id column"),
                batch
                    .column(1)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .expect("Failed to downcast amount column"),
            );
            for (product_id, amount) in product_ids.iter().zip(amounts) {
                if product_id.unwrap() == 1 {
                    assert_eq!(amount.unwrap(), 9)
                } else if product_id.unwrap() == 2 {
                    assert_eq!(amount.unwrap(), 2)
                } else if product_id.unwrap() == 3 {
                    assert_eq!(amount.unwrap(), 4)
                } else {
                    panic!("Unexpected product id")
                }
            }
        }
    }
}

```

## Docker-Compose Local Services

```
services:
  glue:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    restart: always
    volumes:
      - ./.aws:/home/glue_user/.aws:ro
      - ./glue_configs:/home/glue_user/configs:ro
    environment:
      - AWS_PROFILE=glue
      - DISABLE_SSL=true
    ports:
      - 4040:4040
      - 18080:18080
      - 8998:8998
      - 8888:8888
    command: ["/home/glue_user/jupyter/jupyter_start.sh"]
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - my-local-network

  minio:
    image: quay.io/minio/minio
    hostname: bucket001.minio
    restart: always
    volumes:
      - ./minio/data:/data
      - ./minio/init:/docker-entrypoint-init.d
    environment:
      - MINIO_DOMAIN=minio
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-local-network

networks:
  my-local-network:
    driver: bridge

```

**Comment by JanKaul** [comment]
Line 187 should be somewhere after the second insert, right? Does that mean the first insert and test runs fine?

**Comment by ForeverAngry** [comment]
yeah, so the issue was the Glue service i was using.  It only supported a subset of all features.  Thanks for the help!
