### ISSUE TITLE
datafusion_iceberg/examples/insert_csv_minio.rs

### ISSUE THREAD

**Issue by LeoLong0325** [JanKaul/iceberg-rust#92]
Hi, I am trying to implement datafusion_iceberg/examples/insert_csv.rs using minio object storage, but I am having problems. I want to confirm whether this use case is supported by object storage.I only changed the memory storage to object storage, and the other codes remained unchanged:

```rust
    let object_store = ObjectStoreBuilder::S3(
        AmazonS3Builder::new()
            .with_access_key_id("minioadmin".to_string())
            .with_secret_access_key("minioadmin".to_string())
            .with_endpoint("http://192.168.2.181:9000")
            .with_region("us-east-2".to_string()),
    );
    let allow_http = ConfigKey::AWS(AmazonS3ConfigKey::Client(ClientConfigKey::AllowHttp));

    let iceberg_catalog_list = Arc::new(
        SqlCatalogList::new(
            "postgres://leolong:postgres@192.168.2.181:5432/iceberg",
            object_store
                .with_config(allow_certs, "true".to_string())
                .with_config(allow_http, "true".to_string()),
        )
        .await
        .unwrap(),
    );
```
When I run it, I get an error：

```bash
leolong@dc:iceberg-rust-datafusion-jankaul$ cargo run --package datafusion_iceberg --example insert_csv_minio
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/examples/insert_csv_minio`
Catalog created
thread 'main' panicked at catalogs/iceberg-sql-catalog/src/lib.rs:625:50:
called `Result::unwrap()` on an `Err` value: NotSupported("Object store protocol")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It looks like this use case is not supported by object storage. I would like to know why this is the case. 

Looking forward to your reply!

**Comment by ForeverAngry** [comment]
I think maybe your mixing up the configuration of the object store and the sql engine. The way I've used this, is with minio or some s3 compliant object store and then you pass the object store config to the sql catalog. The sql catalog along with datafusion give you a way to read and write iceberg data tables.

**Comment by LeoLong0325** [comment]
I also tried to rewrite other examples for Minio object storage, and other cases can be used normally, but the insert_csv example reported an error after rewriting. I don't know how you rewrite the insert_csv use case using minio instead of memory.

Below is my rewritten dataframe_minio.rs, the code demonstrates how to integrate MinIO object storage with DataFusion Iceberg using Rust.：

```rust
#[tokio::main]
pub(crate) async fn main() {
    let object_store = ObjectStoreBuilder::S3(
        AmazonS3Builder::new()
            .with_access_key_id("minioadmin".to_string())
            .with_secret_access_key("minioadmin".to_string())
            .with_endpoint("http://192.168.2.181:9000"),
    );
    let allow_http = ConfigKey::AWS(AmazonS3ConfigKey::Client(ClientConfigKey::AllowHttp));

    let allow_certs = ConfigKey::AWS(AmazonS3ConfigKey::Client(
        ClientConfigKey::AllowInvalidCertificates,
    ));

    let catalog: Arc<dyn Catalog> = Arc::new(
        SqlCatalog::new(
            "postgres://leolong:postgres@192.168.2.181:5432/iceberg",
            "iceberg",
            object_store
                .with_config(allow_certs, "true".to_string())
                .with_config(allow_http, "true".to_string()),
        )
        .await
        .unwrap(),
    );

    let identifier = Identifier::new(&["public".to_string()], "bank_account_minio");

    // Create iceberg table in the catalog
    ...
    // Write the data from the input dataframe to the table
    ...
    // execute the plan
    ...
```

It works fine：
```bash
leolong@dc:iceberg-rust-datafusion-jankaul$ cargo run --package datafusion_iceberg --example dataframe_minio
   Compiling datafusion_iceberg v0.6.0 (/home/leolong/code/iceberg-rust-datafusion-jankaul/datafusion_iceberg)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 20.07s
     Running `target/debug/examples/dataframe_minio`
Catalog created
batch:RecordBatch { schema: Schema { fields: [Field { name: "sum(warehouse.public.bank_account_minio.bank_account)", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, columns: [PrimitiveArray<Int64>
[
  24000,
]], row_count: 1 }
values:PrimitiveArray<Int64>
[
  24000,
]
```

But this modification logic does not apply to insert_csv.rs.

**Comment by JanKaul** [comment]
The object store protocol not supported error typically happens if the table location is not specified correctly. Did you include a `s3://` prefix to the table location when changing from memory to Minio storage?

You can have a look at the file catalog test from the "copy-if-not-exists" branch: https://github.com/JanKaul/iceberg-rust/blob/copy-if-not-exists/catalogs/iceberg-file-catalog/src/lib.rs#L656
It uses localstack for storage.

**Comment by LeoLong0325** [comment]
I modified the location parameter of the table synchronously. Here is my complete code：

```rust
use std::sync::Arc;

use datafusion::{
    arrow::array::{Float64Array, Int64Array},
    common::tree_node::{TransformedResult, TreeNode},
    execution::{context::SessionContext, SessionStateBuilder},
};
use datafusion_expr::ScalarUDF;
use iceberg_rust::object_store::{ConfigKey, ObjectStoreBuilder};
use iceberg_sql_catalog::SqlCatalogList;

use datafusion_iceberg::{
    catalog::catalog_list::IcebergCatalogList,
    planner::{iceberg_transform, IcebergQueryPlanner, RefreshMaterializedView},
};
use object_store::{
    aws::{AmazonS3Builder, AmazonS3ConfigKey},
    ClientConfigKey,
};

#[tokio::main]
async fn main() {
    let object_store = ObjectStoreBuilder::S3(
        AmazonS3Builder::new()
            .with_access_key_id("minioadmin".to_string())
            .with_secret_access_key("minioadmin".to_string())
            .with_endpoint("http://192.168.2.181:9000")
            .with_region("us-east-2".to_string()),
    );
    let allow_http = ConfigKey::AWS(AmazonS3ConfigKey::Client(ClientConfigKey::AllowHttp));

    let allow_certs = ConfigKey::AWS(AmazonS3ConfigKey::Client(
        ClientConfigKey::AllowInvalidCertificates,
    ));

    let iceberg_catalog_list = Arc::new(
        SqlCatalogList::new(
            "postgres://leolong:postgres@192.168.2.181:5432/iceberg",
            object_store
                .with_config(allow_certs, "true".to_string())
                .with_config(allow_http, "true".to_string()),
        )
        .await
        .unwrap(),
    );

    let catalog_list = {
        Arc::new(
            IcebergCatalogList::new(iceberg_catalog_list.clone())
                .await
                .unwrap(),
        )
    };

    let state = SessionStateBuilder::new()
        .with_default_features()
        .with_catalog_list(catalog_list)
        .with_query_planner(Arc::new(IcebergQueryPlanner {}))
        .build();

    let ctx = SessionContext::new_with_state(state);

    ctx.register_udf(ScalarUDF::from(RefreshMaterializedView::new(
        iceberg_catalog_list,
    )));
    println!("Catalog created");
    let sql = "CREATE EXTERNAL TABLE lineitem ( 
    L_ORDERKEY BIGINT NOT NULL, 
    L_PARTKEY BIGINT NOT NULL, 
    L_SUPPKEY BIGINT NOT NULL, 
    L_LINENUMBER INT NOT NULL, 
    L_QUANTITY DOUBLE NOT NULL, 
    L_EXTENDED_PRICE DOUBLE NOT NULL, 
    L_DISCOUNT DOUBLE NOT NULL, 
    L_TAX DOUBLE NOT NULL, 
    L_RETURNFLAG CHAR NOT NULL, 
    L_LINESTATUS CHAR NOT NULL, 
    L_SHIPDATE DATE NOT NULL, 
    L_COMMITDATE DATE NOT NULL, 
    L_RECEIPTDATE DATE NOT NULL, 
    L_SHIPINSTRUCT VARCHAR NOT NULL, 
    L_SHIPMODE VARCHAR NOT NULL, 
    L_COMMENT VARCHAR NOT NULL ) STORED AS CSV LOCATION 's3://leolongminiobucket/tpch/lineitem.csv' OPTIONS ('has_header' 'false');";

    let plan = ctx.state().create_logical_plan(sql).await.unwrap();

    let transformed = plan.transform(iceberg_transform).data().unwrap();

    ctx.execute_logical_plan(transformed)
        .await
        .unwrap()
        .collect()
        .await
        .expect("Failed to execute query plan.");

    let sql = "CREATE EXTERNAL TABLE warehouse.tpch.lineitem ( 
    L_ORDERKEY BIGINT NOT NULL, 
    L_PARTKEY BIGINT NOT NULL, 
    L_SUPPKEY BIGINT NOT NULL, 
    L_LINENUMBER INT NOT NULL, 
    L_QUANTITY DOUBLE NOT NULL, 
    L_EXTENDED_PRICE DOUBLE NOT NULL, 
    L_DISCOUNT DOUBLE NOT NULL, 
    L_TAX DOUBLE NOT NULL, 
    L_RETURNFLAG CHAR NOT NULL, 
    L_LINESTATUS CHAR NOT NULL, 
    L_SHIPDATE DATE NOT NULL, 
    L_COMMITDATE DATE NOT NULL, 
    L_RECEIPTDATE DATE NOT NULL, 
    L_SHIPINSTRUCT VARCHAR NOT NULL, 
    L_SHIPMODE VARCHAR NOT NULL, 
    L_COMMENT VARCHAR NOT NULL ) STORED AS ICEBERG LOCATION '' PARTITIONED BY ( \"month(L_SHIPDATE)\" );";

    let plan = ctx.state().create_logical_plan(sql).await.unwrap();

    let transformed = plan.transform(iceberg_transform).data().unwrap();

    ctx.execute_logical_plan(transformed)
        .await
        .unwrap()
        .collect()
        .await
        .expect("Failed to execute query plan.");

    let sql = "insert into warehouse.tpch.lineitem select * from lineitem;";

    let plan = ctx.state().create_logical_plan(sql).await.unwrap();

    let transformed = plan.transform(iceberg_transform).data().unwrap();

    ctx.execute_logical_plan(transformed)
        .await
        .unwrap()
        .collect()
        .await
        .expect("Failed to execute query plan.");

    let batches = ctx
        .sql("select sum(L_QUANTITY), L_PARTKEY from warehouse.tpch.lineitem group by L_PARTKEY;")
        .await
        .expect("Failed to create plan for select")
        .collect()
        .await
        .expect("Failed to execute select query");
    println!("{:?}", batches);
    let mut once = false;

    for batch in batches {
        if batch.num_rows() != 0 {
            let (amounts, product_ids) = (
                batch
                    .column(0)
                    .as_any()
                    .downcast_ref::<Float64Array>()
                    .unwrap(),
                batch
                    .column(1)
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .unwrap(),
            );
            for (product_id, amount) in product_ids.iter().zip(amounts) {
                if product_id.unwrap() == 24027 {
                    assert_eq!(amount.unwrap(), 24.0)
                } else if product_id.unwrap() == 63700 {
                    assert_eq!(amount.unwrap(), 8.0)
                }
            }
            once = true
        }
    }

    assert!(once);
}
```
After running, the error I mentioned above will be reported：

```bash
leolong@dc:iceberg-rust-datafusion-jankaul$ cargo run --package datafusion_iceberg --example insert_csv_minio
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/examples/insert_csv_minio`
Catalog created
thread 'main' panicked at catalogs/iceberg-sql-catalog/src/lib.rs:625:50:
called `Result::unwrap()` on an `Err` value: NotSupported("Object store protocol")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JanKaul** [comment]
The S3Tables and the Filesystem catalog automatically generate a location for the table for you. That's why you have to write `LOCATION ''`.
For the SQL catalog you actually have to provide a location where the table is to be stored.

Sorry, the documentation is really lacking.

**Comment by LeoLong0325** [comment]
I added the corresponding location, and it reported another error：

```bash
leolong@dc:iceberg-rust-datafusion-jankaul$ cargo run --package datafusion_iceberg --example insert_csv_minio
   Compiling datafusion_iceberg v0.6.0 (/home/leolong/code/iceberg-rust-datafusion-jankaul/datafusion_iceberg)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 19.56s
     Running `target/debug/examples/insert_csv_minio`
Catalog created
thread 'main' panicked at datafusion_iceberg/examples/insert_csv_minio.rs:114:59:
called `Result::unwrap()` on an `Err` value: External(Iceberg(ObjectStore(NotFound { path: "iceberg/public/lineitem/metadata/00000-d434d103-0b55-4414-91b0-9893752f5459.metadata.json", source: Client { status: 404, body: Some("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>iceberg/public/lineitem/metadata/00000-d434d103-0b55-4414-91b0-9893752f5459.metadata.json</Key><BucketName>leolongminiobucket</BucketName><Resource>/leolongminiobucket/iceberg/public/lineitem/metadata/00000-d434d103-0b55-4414-91b0-9893752f5459.metadata.json</Resource><RequestId>18123D9D331E89A0</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>") } })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I use frostbow to execute the contents of the script, and it can run insert_csv normally.I think the problem occurs in the catalog building stage：

```rust
    let iceberg_catalog_list = Arc::new(
        SqlCatalogList::new(
            "postgres://leolong:postgres@192.168.2.181:5432/iceberg",
            object_store
                .with_config(allow_certs, "true".to_string())
                .with_config(allow_http, "true".to_string()),
        )
        .await
        .unwrap(),
    );

    let catalog_list = {
        Arc::new(
            IcebergCatalogList::new(iceberg_catalog_list.clone())
                .await
                .unwrap(),
        )
    };
```

This code should not work when using filecatalog, at least in frostbow.

**Comment by JanKaul** [comment]
Puhh, it's difficult to say what this could be. Just to be sure, the location that you use for create table includes the `s3://` prefix and the bucket name, like so: `s3://my-bucket/public/lineitem`?

[Here](https://github.com/JanKaul/iceberg-rust/blob/copy-if-not-exists/datafusion_iceberg/tests/integration_trino.rs#L239) is a test with SQL catalog and Localstack S3 storage.

**Comment by LeoLong0325** [comment]
In the above example, I have included the location parameter. When creating the external table, I used `STORED AS CSV LOCATION 's3://leolongminiobucket/tpch/lineitem.csv'`. When creating the iceberg table, I used `STORED AS ICEBERG LOCATION 's3://leolongminiobucket/iceberg/public/lineitem'`. However, the above error is reported:

```bash
leolong@dc:iceberg-rust-datafusion-jankaul$ cargo run --package datafusion_iceberg --example insert_csv_minio
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/examples/insert_csv_minio`
Catalog created
thread 'main' panicked at datafusion_iceberg/examples/insert_csv_minio.rs:114:59:
called `Result::unwrap()` on an `Err` value: External(Iceberg(ObjectStore(NotFound { path: "iceberg/public/lineitem/metadata/00000-d434d103-0b55-4414-91b0-9893752f5459.metadata.json", source: Client { status: 404, body: Some("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>iceberg/public/lineitem/metadata/00000-d434d103-0b55-4414-91b0-9893752f5459.metadata.json</Key><BucketName>leolongminiobucket</BucketName><Resource>/leolongminiobucket/iceberg/public/lineitem/metadata/00000-d434d103-0b55-4414-91b0-9893752f5459.metadata.json</Resource><RequestId>18126F936F28FCEF</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>") } })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It said `The specified key does not exist.`.

**Comment by LeoLong0325** [comment]
When I changed the location of the source table to the location of the local table, my test passed. Thank you for your reply. I will close this issue.

**Comment by JanKaul** [comment]
Sorry for the late reply. I didn't get around to have a look at the issue. I've update the SQL catalog test to use localstack and postgres. So I think [the test](https://github.com/JanKaul/iceberg-rust/blob/main/catalogs/iceberg-sql-catalog/src/lib.rs#L743) should be a good place to start for you example. It uses Postgres as catalog, an external server for object_storage and uses the csv sample data.

**Comment by LeoLong0325** [comment]
OK, thank you again for your reply, my problem has been effectively solved.
